#!/usr/bin/env bash

errors=""
current_date=$(date +"%y%m%d_%H%M")
log_file="/var/log/__APP__/${current_date}.log"
mkdir -p "/var/log/__APP__"

filter_hooks() {
    ls /usr/share/yunohost/hooks/backup/ | grep "\-$1_" | cut -d"-" -f2 | uniq 2>&1
}

# Some apps need to be stopped to be backed up
# https://github.com/search?q=org%3AYunoHost-Apps%20recommended%20to%20make%20your%20backup%20when%20the%20service%20is%20stopped&type=code
apps_to_stop=("synapse" "gitea" "seafile" "sogo" "monitorix" "xwiki")
stop_apps=$(sudo yunohost app setting __APP__ stop_apps)

sudo yunohost app setting __APP__ last_run -v "${current_date}"
sudo yunohost app setting __APP__ state -v "ongoing"

BACKUP_CORE_ONLY=$(sudo yunohost app setting __APP__ backup_core_only)

export BACKUP_CORE_ONLY

# Backup system part conf
conf=$(sudo yunohost app setting __APP__ conf)
if [[ "$conf" = "1" ]]; then
    if ! sudo yunohost backup create -n auto_conf --method __APP___app --system $(filter_hooks conf) >> "$log_file" 2>&1 ; then
        errors+="\nThe backup miserably failed to backup system configurations."
    fi
fi

# Backup system data
data=$(sudo yunohost app setting __APP__ data)
if [[ "$data" = "1" ]]; then
    if ! sudo yunohost backup create -n auto_data --method __APP___app --system $(filter_hooks data) >> "$log_file" 2>&1 ; then
        errors+="\nThe backup miserably failed to backup system data."
    fi
fi

# Read and sanitize the app list:
# - Remove spaces after commas
# - Replace commas with spaces
apps=$(sudo yunohost app setting __APP__ apps | sed 's/,[[:space:]]*/,/g')
apps="${apps//,/ }"

# Initialisation
include_all=false
exclude_list=()
explicit_include_list=()

# Parse app list
for item in $apps; do
    if [[ "$item" == "all" ]]; then
        include_all=true
    elif [[ "$item" =~ ^exclude: ]]; then
        exclude_list+=("${item#exclude:}")
    else
        # If you are not in "all" mode, add to the explicit inclusion list
        if ! $include_all; then
            explicit_include_list+=("$item")
        # If you are in "all" mode and the element is not prefixed with "exclude:", it is an implicit exclusion.
        else
            exclude_list+=("$item")
        fi
    fi
done

# Loop on applications
for application in $(sudo ls /etc/yunohost/apps/); do
    stopped="0"

    # Exclude/Include logic
    if $include_all; then
        # "All" mode: those in exclude_list are excluded.
        if printf '%s\n' "${exclude_list[@]}" | grep -q "^${application}\$"; then
            continue
        fi
    else
        # Explicit inclusion mode: only those in explicit_include_list are included.
        if ! printf '%s\n' "${explicit_include_list[@]}" | grep -q "^${application}\$"; then
            continue
        fi
    fi

    # Verify backup script
    if sudo test ! -f "/etc/yunohost/apps/$application/scripts/backup"; then
        errors+="\nWarning: The application $application has no backup script. This app won't be backed up."
        continue
    fi

    if [[ " ${apps_to_stop[@]} " =~ " ${application} " ]] && [ "$stop_apps" = "1" ]; then
        systemctl stop "$application"
        stopped="1"
    fi

    # Execute backup
    if ! sudo yunohost backup create -n "auto_$application" --method __APP___app --apps "$application" >> "$log_file" 2>&1; then
        errors+="\nThe backup miserably failed to backup $application application."
    fi

    # Start app if stopped
    if [[ "$application" == "1" ]]; then
        systemctl start "$application"
        stopped="0"
    fi
done

#=============================================
# SEND MAIL TO NOTIFY ABOUT FAILED OPERATIONS
#=============================================

# Détection des erreurs critiques
critical_errors="$(grep -iE "Error|Skipped|Fatal|Fail" "$log_file")"

# Détection des warnings
warnings="$(grep -iE "Warning" "$log_file")"

# Send mail on backup (partially) failed
domain=$(hostname)
repository="$(sudo yunohost app setting __APP__ repository)"

# Si des erreurs critiques sont présentes
if [ -n "$critical_errors" ]; then
    errors+="\nSome backup partially failed:\n$critical_errors"
    sudo yunohost app setting __APP__ state -v "failed"
    echo -e "$errors\n\n\n$(cat "$log_file")" | mail -a "Content-Type: text/plain; charset=UTF-8" -s "[__APP__] Backup failed from $domain onto $repository" root
# Si uniquement des warnings sont présents
elif [ -n "$warnings" ]; then
    errors+="\nBackup completed with warnings:\n$warnings"
    sudo yunohost app setting __APP__ state -v "successful_with_warnings"
    echo -e "$errors\n\n\n$(cat "$log_file")" | mail -a "Content-Type: text/plain; charset=UTF-8" -s "[__APP__] Backup completed with warnings from $domain onto $repository" root
# Si tout s'est bien passé
else
    sudo yunohost app setting __APP__ state -v "successful"
fi
