#!/bin/bash

source /usr/share/yunohost/helpers

set -euo pipefail

###
# Fetch information from YNH settings
###
RESTIC_REPOSITORY_BASE=$(yunohost app setting __APP__ repository)
password=$(ynh_app_setting_get --app=__APP__ --key=passphrase)
RESTIC_PASSWORD=$password
HOME="/root"

RESTIC_COMMAND=__INSTALL_DIR__/restic

load_env_file() {
  local env_file="__INSTALL_DIR__/.env"
  if [ -f "$env_file" ]; then
    set -o allexport
    source "$env_file" || { ynh_print_warn "Failed to load environment variables file ($env_file)" >&2; exit 1; }
    set +o allexport
  fi
}

load_ssh_agent() {
  local ssh_key="/root/.ssh/id___APP___ed25519"

  # Verify if ssh-agent is running, start it otherwise
  if [ -z "${SSH_AGENT_PID:-}" ] || ! ps -p "$SSH_AGENT_PID" > /dev/null 2>&1; then
    eval "$(ssh-agent -s)"
  fi

  # Verify if SSH key is already added
  if ! ssh-add -l | grep -q "$(basename "$ssh_key")"; then
    if [ -f "$ssh_key" ]; then
      if ! ssh-add -q "$ssh_key" >&2; then
        ynh_print_warn "Failed to add SSH key to agent ($ssh_key)" >&2
      fi
    else
      ynh_print_warn "Failed to find SSH key ($ssh_key)" >&2
    fi
  fi
  trap 'ssh-agent -k > /dev/null' EXIT
}

do_need_mount() {
    local work_dir="$1"
    local name="$2"
    local size="$3"
    local description="$4"

    export RESTIC_PASSWORD
    export RESTIC_REPOSITORY=${RESTIC_REPOSITORY_BASE}/$name
    export HOME

    load_env_file
    load_ssh_agent

    if ! $RESTIC_COMMAND cat config > /dev/null 2>&1; then
      ynh_print_info "The Restic repository isn't initialized yet"
      if ! $RESTIC_COMMAND init -q >&2; then
        ynh_print_warn "Failed to initialize the new Restic repository" >&2
        exit 1
      fi
      ynh_print_info "The Restic repository was successfuly initialized" >&2
    fi
}

do_backup() {
    local work_dir="$1"
    local name="$2"
    local size="$3"
    local description="$4"

    export RESTIC_PASSWORD
    export RESTIC_REPOSITORY=${RESTIC_REPOSITORY_BASE}/$name
    export HOME

    local current_date
    current_date=$(date +"%d_%m_%y_%H:%M")
    load_env_file
    load_ssh_agent
    pushd "$work_dir" > /dev/null

    if ! $RESTIC_COMMAND backup -q ./ >&2; then
      ynh_print_warn "Failed to upload backup with Restic"
      exit 1
    fi

    local forget_policy="$(yunohost app setting __APP__ forget_policy)"
    if ! $RESTIC_COMMAND forget -q $forget_policy >&2; then
      ynh_print_warn "Failed to apply backup retention policy"
      exit 1
    fi
    popd > /dev/null
}

work_dir=$2
name=$3
size=$5
description=$6

case "$1" in
  need_mount)
    do_need_mount "$work_dir" "$name" "$size" "$description"
    ;;
  backup)
    do_backup "$work_dir" "$name" "$size" "$description"
    ;;
  mount)
    do_need_mount "$work_dir" "$name" "$size" "$description"
    ;;
  *)
    ynh_print_warn "Unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0
