#!/usr/bin/env bash

errors=""
current_date=$(date +"%y%m%d_%H%M")
log_file="/var/log/__APP__/${current_date}.log"
err_file="/var/log/__APP__/${current_date}.err"
mkdir -p "/var/log/__APP__"

filter_hooks() {
    ls /usr/share/yunohost/hooks/backup/ | grep "\-$1_" | cut -d"-" -f2 | uniq 2>> "$err_file"
}

sudo yunohost app setting __APP__ last_run -v "${current_date}"
sudo yunohost app setting __APP__ state -v "ongoing"

BACKUP_CORE_ONLY=$(sudo yunohost app setting __APP__ backup_core_only)

export BACKUP_CORE_ONLY

# Backup system part conf
conf=$(sudo yunohost app setting __APP__ conf)
if [[ "$conf" = "1" ]]; then
    if ! sudo yunohost backup create -n auto_conf --method __APP___app --system $(filter_hooks conf) 2>> "$err_file" >> "$log_file" ; then
        errors+="\nThe backup miserably failed to backup system configurations."
    fi
fi

# Backup system data
data=$(sudo yunohost app setting __APP__ data)
if [[ "$data" = "1" ]]; then
    if ! sudo yunohost backup create -n auto_data --method __APP___app --system $(filter_hooks data) 2>> "$err_file" >> "$log_file" ; then
        errors+="\nThe backup miserably failed to backup system data."
    fi
fi

# Read and sanitize the app list:
# - Remove spaces after commas
# - Replace commas with spaces
apps=$(sudo yunohost app setting __APP__ apps | sed 's/,[[:space:]]*/,/g')
apps="${apps//,/ }"

# Initialisation
include_all=false
exclude_list=()
explicit_include_list=()

# Parse app list
for item in $apps; do
    if [[ "$item" == "all" ]]; then
        include_all=true
    elif [[ "$item" =~ ^exclude: ]]; then
        exclude_list+=("${item#exclude:}")
    else
        # If you are not in "all" mode, add to the explicit inclusion list
        if ! $include_all; then
            explicit_include_list+=("$item")
        # If you are in "all" mode and the element is not prefixed with "exclude:", it is an implicit exclusion.
        else
            exclude_list+=("$item")
        fi
    fi
done

# Loop on applications
for application in $(sudo ls /etc/yunohost/apps/); do
    # Exclude/Include logic
    if $include_all; then
        # "All" mode: those in exclude_list are excluded.
        if printf '%s\n' "${exclude_list[@]}" | grep -q "^${application}\$"; then
            continue
        fi
    else
        # Explicit inclusion mode: only those in explicit_include_list are included.
        if ! printf '%s\n' "${explicit_include_list[@]}" | grep -q "^${application}\$"; then
            continue
        fi
    fi

    # Verify backup script
    if sudo test ! -f "/etc/yunohost/apps/$application/scripts/backup"; then
        errors+="\nWarning: The application $application has no backup script. This app won't be backed up."
        continue
    fi

    # Execute backup
    if ! sudo yunohost backup create -n "auto_$application" --method __APP___app --apps "$application" 2>> "$err_file" >> "$log_file"; then
        errors+="\nThe backup miserably failed to backup $application application."
    fi
done

#=============================================
# SEND MAIL TO NOTIFY ABOUT  FAILED OPERATIONS
#=============================================

partial_errors="$(cat "$log_file" | grep -E "Error|Skipped")"
if [ -n "$partial_errors" ]; then
    errors+="\nSome backup partially failed:\n$partial_errors"
fi

# Send mail on backup (partially) failed
domain=$(hostname)
repository="$(sudo yunohost app setting __APP__ repository)"
if [[ -n "$errors" ]]; then
    sudo yunohost app setting __APP__ state -v "failed"
    cat <(echo -e "$errors\n\n\n") "$log_file" "$err_file" | mail -a "Content-Type: text/plain; charset=UTF-8" -s "[__APP__] Backup failed from $domain onto $repository" root
else
    sudo yunohost app setting __APP__ state -v "successful"
fi
