#!/usr/bin/env bash

errors=""
current_date=$(date +"%y%m%d_%H%M")
log_file="/var/log/__APP__/${current_date}.log"
err_file="/var/log/__APP__/${current_date}.err"
mkdir -p "/var/log/__APP__"

filter_hooks() {
    ls /usr/share/yunohost/hooks/backup/ | grep "\-$1_" | cut -d"-" -f2 | uniq 2>> "$err_file"
}

CHECK_READ_DATA=${1:-0}


# Check system part conf
conf=$(sudo yunohost app setting __APP__ conf)
if [[ "$conf" = "1" ]]; then
    if ! sudo __INSTALL_DIR__/check_method auto_conf ${CHECK_READ_DATA} 2>> "$err_file" >> "$log_file" ; then
        errors+="\nRestic miserably failed to check backups for system configurations."
    fi
fi

# Check system data
data=$(sudo yunohost app setting __APP__ data)
if [[ "$data" = "1" ]]; then
    if ! sudo __INSTALL_DIR__/check_method auto_data ${CHECK_READ_DATA} 2>> "$err_file" >> "$log_file" ; then
        errors+="\nRestic miserably failed to check backups for system data."
    fi
fi

# Read and sanitize the app list:
# - Remove spaces after commas
# - Replace commas with spaces
apps=$(sudo yunohost app setting __APP__ apps | sed 's/,[[:space:]]*/,/g')
apps="${apps//,/ }"

include_all=false
exclude_list=()
explicit_include_list=()

# Parse app list
for item in $apps; do
    if [[ "$item" == "all" ]]; then
        include_all=true
    elif [[ "$item" =~ ^exclude: ]]; then
        exclude_list+=("${item#exclude:}")
    else
        # If you are not in "all" mode, add to the explicit inclusion list
        if ! $include_all; then
            explicit_include_list+=("$item")
        # If you are in "all" mode and the element is not prefixed with "exclude:", it is an implicit exclusion.
        else
            exclude_list+=("$item")
        fi
    fi
done

# Loop on applications
for application in $(sudo ls /etc/yunohost/apps/); do
    # Exclude/Include logic
    if $include_all; then
        # "All" mode: those in exclude_list are excluded.
        if printf '%s\n' "${exclude_list[@]}" | grep -q "^${application}\$"; then
            continue
        fi
    else
        # Explicit inclusion mode: only those in explicit_include_list are included.
        if ! printf '%s\n' "${explicit_include_list[@]}" | grep -q "^${application}\$"; then
            continue
        fi
    fi

    if sudo test ! -f "/etc/yunohost/apps/$application/scripts/backup" ; then
        continue
    fi

    if ! sudo __INSTALL_DIR__/check_method auto_${application} ${CHECK_READ_DATA} 2>> "$err_file" >> "$log_file" ; then
        errors+="\nRestic miserably failed to check backups for $application application."
    fi
done

#=============================================
# SEND MAIL TO NOTIFY ABOUT  FAILED OPERATIONS
#=============================================

partial_errors="$(cat "$log_file" | grep -E "Error|Skipped")"
if [ -n "$partial_errors" ]; then
    errors+="\nSome backup checks partially failed:\n$partial_errors"
fi

# Send mail on backup (partially) failed
domain=$(hostname)
repository="$(sudo yunohost app setting __APP__ repository)"
if [[ -n "$errors" ]]; then
    sudo yunohost app setting __APP__ state -v "failed"
    cat <(echo -e "$errors\n\n\n") "$log_file" "$err_file" | mail -a "Content-Type: text/plain; charset=UTF-8" -s "[__APP__] Backup checks failed from $domain onto $repository" root
else
    sudo yunohost app setting __APP__ state -v "successful"
fi
