#!/bin/bash

source /usr/share/yunohost/helpers
source /var/www/__APP__/helpers

set -e

RESTIC_REPOSITORY_BASE=$(yunohost app setting __APP__ repository)
password=$(ynh_app_setting_get --app=__APP__ --key=passphrase)
RESTIC_PASSWORD=$password
RESTIC_COMMAND=__INSTALL_DIR__/restic

do_check() {
    local name="$1"
    local check_read_data="$2"

    export RESTIC_PASSWORD
    export RESTIC_REPOSITORY=${RESTIC_REPOSITORY_BASE}/$name

    load_env_file
    load_ssh_agent

    if [ "$check_read_data" -eq 1 ]; then
        $RESTIC_COMMAND check --read-data -q
    else
        $RESTIC_COMMAND check -q
    fi

    return $?
}

name=$1
check_read_data=${2:-0}

do_check "${name}" "${check_read_data}"

exit 0
