#!/bin/bash

load_env_file() {
  local env_file="__INSTALL_DIR__/.env"
  if [ -f "$env_file" ]; then
    set -o allexport
    source "$env_file" || { echo "Failed to load environment variables file ($env_file)" >&2; exit 1; }
    set +o allexport
  fi
}

load_ssh_agent() {
  local ssh_key="/root/.ssh/id___APP___ed25519"

  # Verify if ssh-agent is running, start it otherwise
  if [ -z "${SSH_AGENT_PID:-}" ] || ! ps -p "$SSH_AGENT_PID" > /dev/null 2>&1; then
    eval "$(ssh-agent -s)"
  fi

  # Verify if SSH key is already added
  if ! ssh-add -l | grep -q "$(basename "$ssh_key")"; then
    if [ -f "$ssh_key" ]; then
      if ! ssh-add -q "$ssh_key" >&2; then
        echo "Failed to add SSH key to agent ($ssh_key)" >&2
      fi
    else
      echo "Failed to find SSH key ($ssh_key)" >&2
    fi
  fi
  trap 'ssh-agent -k > /dev/null' EXIT
}
