#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================

for suffix in "${systemd_services_suffixes[@]}"; do
    ynh_backup "/etc/systemd/system/$app$suffix.timer"
    ynh_backup "/etc/systemd/system/$app$suffix.service"
done

ynh_backup "/etc/yunohost/hooks.d/backup_method/05-${app}_app"
ynh_backup "/etc/sudoers.d/$app"

ynh_backup "/root/.ssh/id_${app}_ed25519"
ynh_backup "/root/.ssh/id_${app}_ed25519.pub"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
