#!/bin/bash

source /usr/share/yunohost/helpers
source /var/www/$app/helpers

ynh_abort_if_errors

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEY
#=================================================

get__info() {
        cat << EOF
ask:
  en: "**Backup state**: ${state}

    **Last run**: ${last_run}"
EOF
    if [ "${state}" == "failed" ]; then
        cat << EOF
style: "danger"
EOF
    elif [ "${state}" == "successful_with_warnings" ]; then
        cat << EOF
style: "warning"
EOF
    elif [ "${state}" == "successful" ]; then
        cat << EOF
style: "success"
EOF
    else
        cat << EOF
style: "info"
EOF
    fi
}

get__ssh_public_key() {
    cat << EOF
ask:
  en: "**Public key**: \`$(cat /root/.ssh/id_${app}_ed25519.pub || echo '')\`"
EOF
}

get__data_multimedia() {
    if [ -e /home/yunohost.multimedia/.nobackup ]; then
        echo false
    else
        echo true
    fi
}

#=================================================
# SPECIFIC VALIDATORS FOR TOML SHORT KEYS
#=================================================
validate__on_calendar() {
    (systemd-analyze calendar $on_calendar > /dev/null) ||
        echo 'Please follow systemd OnCalendar format: https://man.archlinux.org/man/systemd.time.7#CALENDAR_EVENTS'
}
validate__check_on_calendar() {
    (systemd-analyze calendar $check_on_calendar > /dev/null) ||
        echo 'Please follow systemd OnCalendar format: https://man.archlinux.org/man/systemd.time.7#CALENDAR_EVENTS'
}
validate__check_read_data_on_calendar() {
    (systemd-analyze calendar $check_read_data_on_calendar > /dev/null) ||
        echo 'Please follow systemd OnCalendar format: https://man.archlinux.org/man/systemd.time.7#CALENDAR_EVENTS'
}

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================

set__data_multimedia() {
    if [ "$data_multimedia" == "0" ]; then
        mkdir -p /home/yunohost.multimedia/
        touch /home/yunohost.multimedia/.nobackup
    else
        if [ -e /home/yunohost.multimedia/.nobackup ]; then
            ynh_safe_rm /home/yunohost.multimedia/.nobackup
        fi
    fi
}

#=================================================
# SPECIFIC ACTIONS FOR TOML SHORT KEY
#=================================================

run__check_connection() {
    local output
    local exit_code
    pushd "/var/www/$app"
    load_env_file
    load_ssh_agent
    export RESTIC_PASSWORD=$passphrase
    set +e
    output=$(./restic -r "$repository/auto_conf" cat config 2>&1)
    exit_code=$?
    set -e
        case $exit_code in
        0)
            ynh_print_info "Connection successfull, repository is already initialized."
            ;;
        10)
            ynh_print_info "Connection successfull, repository does not exists yet."
            ;;
        1)
            if [[ "$output" == *"repository does not exist"* ]]; then
                ynh_print_info "Connection successfull, repository does not exists yet."
            else
                ynh_print_warn "Action failed with code $exit_code. Details : $output"
            fi
            ;;
        *)
            ynh_print_warn "Action failed with code $exit_code. Details : $output"
            ;;
    esac

    popd
}

run__now() {
    systemctl start --no-block $app
}

#=================================================
# GENERIC FINALIZATION
#=================================================
ynh_app_config_run $1