#!/bin/bash

source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEY
#=================================================

get__info() {
        cat << EOF
ask:
  en: "**Backup state**: ${old[state]}

    **Last run**: ${old[last_run]}"
EOF
    if [ "${old[state]}" == "failed" ]; then
        cat << EOF
style: "danger"
EOF
    elif [ "${old[state]}" == "successful" ]; then
        cat << EOF
style: "success"
EOF
    else
        cat << EOF
style: "info"
EOF
    fi
}

get__ssh_public_key() {
    cat << EOF
ask:
  en: "**Public key**: \`$(cat /root/.ssh/id_${app}_ed25519.pub || echo '')\`"
EOF
}

get__data_multimedia() {
    if [ -e /home/yunohost.multimedia/.nobackup ]; then
        echo false
    else
        echo true
    fi
}

get__conf() {
    ynh_app_setting_get --app=$app --key=conf
}

get__forget_policy() {
    ynh_app_setting_get --app=$app --key=forget_policy
}

#=================================================
# SPECIFIC VALIDATORS FOR TOML SHORT KEYS
#=================================================
validate__on_calendar() {
    (systemd-analyze calendar $on_calendar > /dev/null) ||
        echo 'Please follow systemd OnCalendar format: https://man.archlinux.org/man/systemd.time.7#CALENDAR_EVENTS'
}
validate__check_on_calendar() {
    (systemd-analyze calendar $check_on_calendar > /dev/null) ||
        echo 'Please follow systemd OnCalendar format: https://man.archlinux.org/man/systemd.time.7#CALENDAR_EVENTS'
}
validate__check_read_data_on_calendar() {
    (systemd-analyze calendar $check_read_data_on_calendar > /dev/null) ||
        echo 'Please follow systemd OnCalendar format: https://man.archlinux.org/man/systemd.time.7#CALENDAR_EVENTS'
}

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================

set__data_multimedia() {
    if [ "$data_multimedia" == "0" ]; then
        mkdir -p /home/yunohost.multimedia/
        touch /home/yunohost.multimedia/.nobackup
    else
        ynh_safe_rm /home/yunohost.multimedia/.nobackup
    fi
}

set__conf() {
    if [ -n "${conf}" ]
    then
        # Update the config of the app
        ynh_app_setting_set --app=$app --key=conf --value=$conf
    fi
}

set__on_calendar() {
    ynh_app_setting_set --key="on_calendar" --value="$on_calendar"
    ynh_config_add --template="systemd.timer" --destination="/etc/systemd/system/$app.timer"
    systemctl daemon-reload
}

set__check_on_calendar() {
    ynh_app_setting_set --key="check_on_calendar" --value="$check_on_calendar"
    ynh_config_add --template="systemd_check.timer" --destination="/etc/systemd/system/${app}_check.timer"
    systemctl daemon-reload
}

set__check_read_data_on_calendar() {
    ynh_app_setting_set --key="check_read_data_on_calendar" --value="$check_read_data_on_calendar"
    ynh_config_add --template="systemd_check_read_data.timer" --destination="/etc/systemd/system/${app}_check_read_data.timer"
    systemctl daemon-reload
}

set__forget_policy() {
    ynh_app_setting_set --key="forget_policy" --value="$forget_policy"
}

load_env_file() {
  local env_file="$app/.env"
  if [ -f "$env_file" ]; then
    set -o allexport
    source "$env_file" || { echo "Erreur : Impossible de charger le fichier d'environnement $env_file" >&2; exit 1; }
    set +o allexport
  fi
}

load_ssh_agent() {
  local ssh_key="/root/.ssh/id${$app}ed25519"

  # Verify if ssh-agent is running, start it otherwise
  if [ -z "${SSH_AGENT_PID:-}" ] || ! ps -p "$SSH_AGENT_PID" > /dev/null 2>&1; then
    eval "$(ssh-agent -s)" || { echo "Erreur : Impossible de démarrer ssh-agent" >&2; exit 1; }
  fi

  # Verify if SSH key is already added
  if ! ssh-add -l | grep -q "$(basename "$ssh_key")"; then
    if [ -f "$ssh_key" ]; then
      ssh-add "$ssh_key" > /dev/null 2>&1 || echo "Erreur : Impossible d'ajouter la clé SSH $ssh_key" >&2
    else
      echo "Erreur : Clé SSH $ssh_key introuvable" >&2
    fi
  fi
  trap 'ssh-agent -k > /dev/null' EXIT
}

run__check_connection() {
    local output
    local exit_code
    ynh_print_info "Checking connection..."
    pushd "/var/www/$app"
    load_env_file
    load_ssh_agent
    output=$(./restic -r "$repository/auto_conf" cat config 2>&1)
    exit_code=$?
        case $exit_code in
        0)
            ynh_print_info "Le dépôt est déjà initialisé."
            ;;
        10)
            ynh_print_info "Le dépôt n'existe pas (code $exit_code)."
            ;;
        1)
            if [[ "$output" == *"repository does not exist"* ]]; then
                ynh_print_info "Le dépôt n'existe pas mais la commande n'a pas échoué (ancienne version de Restic ?)."
            else
                ynh_print_warn "La commande a échoué avec le code $exit_code. Détails : $output"
            fi
            ;;
        *)
            ynh_print_warn "La commande a échoué avec le code $exit_code. Détails : $output"
            ;;
    esac

    popd
    return $exit_code
}

#=================================================
# GENERIC FINALIZATION
#=================================================
ynh_app_config_run $1