#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

# passwords aren't saved by default
ynh_app_setting_set --key=passphrase --value="$passphrase"

#=================================================
# INSTALL RESTIC
#=================================================
ynh_script_progression "Installing Restic..."

ynh_setup_source --source_id=main --dest_dir="$install_dir"
chmod +x "$install_dir/restic"

_gen_and_save_public_key

_set_ssh_config

#=================================================
# SETUP THE BACKUP METHOD
#=================================================
ynh_script_progression "Setting up backup method..."

mkdir -p /etc/yunohost/hooks.d/backup
mkdir -p /etc/yunohost/hooks.d/backup_method
mkdir -p /usr/share/yunohost/backup_method

## Backup method
_ynh_config_add_j2 --template="backup_method.j2" --destination="/etc/yunohost/hooks.d/backup_method/05-${app}_app"
chmod go=--- "/etc/yunohost/hooks.d/backup_method/05-${app}_app"

_ynh_config_add_j2 --template="backup-with-restic.j2" --destination="$install_dir/backup-with-restic"
chmod u+x "$install_dir/backup-with-restic"

## Check method
_ynh_config_add_j2 --template="check_method.j2" --destination="$install_dir/check_method_restic"

_ynh_config_add_j2 --template="check-restic.j2" --destination="$install_dir/check-restic"
chmod u+x "$install_dir/check-restic"

## Backup log script
_ynh_config_add_j2 --template="restic_log.j2" --destination="$install_dir/restic_log"
chmod u+x "$install_dir/restic_log"

# Check log script
_ynh_config_add_j2 --template="restic_check_log.j2" --destination="$install_dir/restic_check_log"
chmod u+x "$install_dir/restic_check_log"

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R "$app:$app" "$install_dir"
#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Systemd services and timers
for suffix in "${systemd_services_suffixes[@]}"; do
    ynh_config_add_systemd --service="$app$suffix" --template="systemd$suffix.service"
    _ynh_config_add_j2 --template="systemd$suffix.timer.j2" --destination="/etc/systemd/system/$app$suffix.timer"
    ynh_systemctl --service="${app}$suffix.service" --action="disable"
    systemctl enable --quiet "${app}$suffix.timer"
    ynh_systemctl --service="${app}$suffix.timer" --action="start"

    yunohost service add "$app$suffix" --description="Restic backup program ($app$suffix)" \
        --test_status="systemctl show $app$suffix.service  -p ActiveState --value | grep -v failed"
done

ynh_config_add --template="sudoer" --destination="/etc/sudoers.d/$app"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown root:root "/etc/sudoers.d/$app"

ynh_config_add_logrotate "/var/log/restic_backup_${app}.log"
ynh_config_add_logrotate "/var/log/restic_backup_${app}.err"
ynh_config_add_logrotate "/var/log/restic_check_${app}.log"
ynh_config_add_logrotate "/var/log/restic_check_${app}.err"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
