#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

# passwords aren't saved by default
ynh_app_setting_set --key=passphrase --value="$passphrase"

# these parameters are too technical to be requested from the user
check_on_calendar="Sat *-*-8..31 3:15:00"
ynh_app_setting_set --key=check_on_calendar --value="$check_on_calendar"

check_read_data_on_calendar="Sat *-*-1..7 3:15:00"
ynh_app_setting_set --key=check_read_data_on_calendar --value="$check_read_data_on_calendar"

ynh_app_setting_set --key=last_run --value="never"
ynh_app_setting_set --key=state --value="todo"


#=================================================
# INSTALL RESTIC
#=================================================
ynh_script_progression "Installing Restic..."

ynh_setup_source --source_id=main --dest_dir="$install_dir"
bunzip2 -d -f "$install_dir/restic.bz2"
chmod +x "$install_dir/restic"

_gen_and_save_public_key

#=================================================
# SETUP THE BACKUP METHOD
#=================================================
ynh_script_progression "Setting up backup method..."

mkdir -p /etc/yunohost/hooks.d/backup
mkdir -p /etc/yunohost/hooks.d/backup_method
mkdir -p /usr/share/yunohost/backup_method

## Backup method
ynh_config_add --template="backup_method" --destination="/etc/yunohost/hooks.d/backup_method/05-${app}_app"
chmod go=--- "/etc/yunohost/hooks.d/backup_method/05-${app}_app"

ynh_config_add --template="backup-with-restic" --destination="$install_dir/backup-with-restic"
chmod u+x "$install_dir/backup-with-restic"

## Check method
ynh_config_add --template="check_method" --destination="$install_dir/check_method"
chmod u+x "$install_dir/check_method"

ynh_config_add --template="check-with-restic" --destination="$install_dir/check-with-restic"
chmod u+x "$install_dir/check-with-restic"

## Backup log script
ynh_config_add --template="restic_backup_log" --destination="$install_dir/restic_backup_log"
chmod u+x "$install_dir/restic_backup_log"

# Check log script
ynh_config_add --template="restic_check_log" --destination="$install_dir/restic_check_log"
chmod u+x "$install_dir/restic_check_log"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations..."

# Systemd services and timers
for suffix in "${systemd_services_suffixes[@]}"; do
    ynh_config_add_systemd --service="$app$suffix" --template="systemd$suffix.service"
    ynh_config_add --template="systemd$suffix.timer" --destination="/etc/systemd/system/$app$suffix.timer"
    systemctl disable --quiet $app$suffix.service
    systemctl enable --quiet "${app}$suffix.timer"
    ynh_systemctl --service="${app}$suffix.timer" --action="start"

    yunohost service add "$app$suffix" --description="Restic backup program ($app$suffix)" \
        --test_status="systemctl show $app$suffix.service  -p ActiveState --value | grep -v failed"
done

ynh_config_add --template="sudoer" --destination="/etc/sudoers.d/$app"
chown root:root "/etc/sudoers.d/$app"

ynh_config_add_logrotate

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
