#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Systemd services and timers
for suffix in "${systemd_services_suffixes[@]}"; do
    yunohost service remove "$app$suffix"
    ynh_systemctl --service="$app$suffix.timer" --action="stop"
    ynh_systemctl --service="$app$suffix.timer" --action="disable"
    ynh_config_remove_systemd "$app$suffix"
    ynh_safe_rm "/etc/systemd/system/$app$suffix.timer"
done

ynh_config_remove_logrotate

# Remove sudoers
ynh_safe_rm "/etc/sudoers.d/$app"

ynh_safe_rm "/etc/yunohost/hooks.d/backup_method/05-${app}_app"

#=================================================
# REMOVE SSH CONFIG
#=================================================
ynh_script_progression "Removing ssh config"

if [ -f "/root/.ssh/config" ]; then
    sed -e "/begin ${app}/,/end ${app}/{/.*/d}" /root/.ssh/config -i || true
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
