#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

_gen_and_save_public_key

#=================================================
# ACTIVATE BACKUP METHODS
#=================================================
ynh_script_progression "Setting up backup method..."

mkdir -p /etc/yunohost/hooks.d/backup
mkdir -p /etc/yunohost/hooks.d/backup_method
mkdir -p /usr/share/yunohost/backup_method

ynh_restore "/etc/yunohost/hooks.d/backup_method/05-${app}_app"
chmod go=--- "/etc/yunohost/hooks.d/backup_method/05-${app}_app"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/sudoers.d/$app"
chown root:root "/etc/sudoers.d/$app"

ynh_restore "/root/.ssh/id_${app}_ed25519"
ynh_restore "/root/.ssh/id_${app}_ed25519.pub"

for suffix in "${systemd_services_suffixes[@]}"; do
    ynh_restore "/etc/systemd/system/$app$suffix.timer"
    ynh_restore "/etc/systemd/system/$app$suffix.service"
	systemctl enable --quiet "$app$suffix.timer"
	ynh_systemctl --service="$app$suffix.timer" --action="start"

    yunohost service add "$app$suffix" --description="Restic backup program ($app$suffix)" \
        --test_status="systemctl show $app$suffix.service  -p ActiveState --value | grep -v failed"
done

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
